apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  #googleCloudBuild:
  #projectId: ticketing-dev-331717
  artifacts:
    - image: jiaqiwang118/auth
      #image: us.gcr.io/ticketing-dev-331717/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jiaqiwang118/client
      #image: us.gcr.io/ticketing-dev-331717/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: jiaqiwang118/tickets
      #image: us.gcr.io/ticketing-dev-331717/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jiaqiwang118/orders
      #image: us.gcr.io/ticketing-dev-331717/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jiaqiwang118/expiration
      #image: us.gcr.io/ticketing-dev-331717/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jiaqiwang118/payments
      #image: us.gcr.io/ticketing-dev-331717/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
