apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ticketing-app-com-tls
  namespace: default
spec:
  secretName: ticketing-app-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ticketing-app.com
  dnsNames:
    - ticketing-app.com
    - www.ticketing-app.com
