name: Build and Deploy Tickets Service to GKE

on:
  push:
    branches:
      - master
    paths:
      - 'tickets/**'

env:
  PROJECT_ID: ticketing-334302
  GKE_CLUSTER: ticketing # Add your cluster name here.
  GKE_ZONE: us-east1-b # Add your cluster zone here.
  DEPLOYMENT_NAME: ticketing # Add your deployment name here.
  IMAGE: static-site

jobs:
  deploy-tickets:
    name: Deploy Tickets Service
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init gcloud CLI
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ticketing-334302

      - name: Config Docker
        run: gcloud --quiet auth configure-docker

      - name: Build Docker Container
        run: |-
          cd tickets && docker build -t jiaqiwang118/tickets .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push jiaqiwang118/tickets

      - name: Deploy to GKE
        run: |-
          gcloud container clusters get-credentials ticketing --zone=us-east1-b
          kubectl rollout restart deployment/tickets-depl
          kubectl get services -o wide
