name: deploy-manifests
on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
jobs:
  deploy-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ticketing-334302
      - run: gcloud container clusters get-credentials ticketing --zone=us-east1-b
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
